version: '3.7'

services:
  docker-example:
    image: deep/dockerexample:0.0.1-SNAPSHOT
    #build:
    #context: .
    #dockerfile: Dockerfile
    ports:
    - "9000:9000"
    restart: always
    depends_on:
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: sample_test
      RDS_USERNAME: sample_user
      RDS_PASSWORD: Sample@123
    networks:
      - spring-mysql-network

  mysql:
    image: mysql:5.7
    ports:
    - "4000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: Sample@123
      MYSQL_DATABASE: sample_test
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - spring-mysql-network
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  spring-mysql-network:

